# Generated by Django 5.2.7 on 2025-12-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='productos/default.jpg', upload_to='productos/'),
        ),
    ]
