# Generated by Django 5.2.8 on 2025-12-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='imagen_Referencia',
            field=models.ImageField(blank=True, upload_to='productos_referencia'),
        ),
    ]
