# Generated by Django 5.2.5 on 2025-12-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0006_alter_pedido_imagen_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='imagen_Referencia',
            field=models.ImageField(blank=True, upload_to='productos'),
        ),
    ]
